Feature static files
avoevodin/django_tutorial pull request #12
Opened 2021-03-20 16:39 UTC by avoevodin

#5

2021-03-20 16:49 UTC, iliadmitriev requested changes

2021-03-20 16:49 UTC, iliadmitriev commented on mysite/uwsgi.ini
> +enable-threads=False
Why did you disable threads?

2021-03-21 11:09 UTC, avoevodin commented on mysite/uwsgi.ini
> +enable-threads=False
I was just testing )

2021-03-21 15:11 UTC, iliadmitriev commented on requirements.txt
> +click==7.1.2
to be deleted

2021-03-21 15:11 UTC, iliadmitriev commented on requirements.txt
> +h11==0.12.0
to be deleted

2021-03-21 15:12 UTC, iliadmitriev approved these changes

2021-03-21 15:12 UTC, merged